sudo: false
language: python
env:
  - RASTERIO_VERSION=0.26.0
addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
      - libgdal-dev
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - python-numpy
      - python-scipy
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse
before_install:
  - curl -L https://github.com/mapbox/rasterio/releases/download/$RASTERIO_VERSION/rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz > /tmp/wheelhouse.tar.gz
  - tar -xzvf /tmp/wheelhouse.tar.gz -C $HOME
install:
  - pip install cython>=0.21.2
  - pip install --use-wheel --find-links=$HOME/wheelhouse -r requirements-dev.txt --cache-dir $HOME/.pip-cache
  - pip install --use-wheel --find-links=$HOME/wheelhouse -r requirements.txt --cache-dir $HOME/.pip-cache
  - pip install --use-wheel --find-links=$HOME/wheelhouse -e . --cache-dir $HOME/.pip-cache
script:
  - py.test --cov clover --cov-report term-missing
after_success:
  - coveralls
